---
# ------------------------------------------------------------------------------------------------------------------------
sap_sid: 
sap_instancenum: 
sap_hostname: 

# ------------------------------------------------------------------------------------------------------------------------
# -----------------------------URLs for HANA DB Installation--------------------------------------------------------------
# Default URLs
# url_sapcar:
# url_hdbserver:
# url_hcmt: https://softwaredownloads.sap.com/file/0020000000392012021
# using own accessible storage account:
url_sapcar: https://s4hanamedia.blob.core.windows.net/media/SAPCAR_1311-80000935.EXE
url_hdbserver: https://s4hanamedia.blob.core.windows.net/media/IMDB_SERVER20_046_0-80002031.SAR
url_hcmt: https://s4hanamedia.blob.core.windows.net/media/HCMT_055_0-80003261.SAR 

url_cockpit:
url_di_core:
url_portal_services:
url_shine_xsa:
url_xs_services:
url_xsa_runtime:
url_xsa_hrtt:
url_xsa_webide:
url_xsa_mta:

url_retries_delay: 10
url_timeout: 30
url_retries_cnt: 20

install_cockpit: false
install_shine: false
install_xsa: false

email_shine: "shinedemo@microsoft.com"

# ------------------------------------------------------------------------------------------------------------------------
# -----------------------------URL for the Azure HANA Backint Integration Script------------------------------------------
# Default:
url_msawb_plugin: https://s4hanamedia.blob.core.windows.net/media/msawb-plugin-config-com-sap-hana.sh
# using own accessible storage account is required when internet access is blocked, example:
# url_msawb_plugin: https://<your-own-storage-name>.blob.core.windows.net/sapdeployments/msawb-plugin-config-com-sap-hana.sh
# ------------------------------------------------------------------------------------------------------------------------